### ISSUE TITLE
return_of_invalid_type_from_closure

### ISSUE THREAD

**Issue by Khalifares** [htsuruo/flutter-admin-dashboard-template#2]
After upgrading the dependencies I'm getting this error on the dashboard_page.dart : 

The return type 'ColoredBox' isn't a 'TableViewCell', as required by the closure's context.

<img width="1008" alt="Screenshot 2024-02-09 at 18 13 30" src="https://github.com/htsuruo/flutter-admin-dashboard-template/assets/48349918/5a701b42-96cf-4b81-ac44-1ea0888ba716">

**Comment by htsuruo** [comment]
@Khalifares 

Thanks for reporting.
Fixed it #3 .

You can run this template with latest dependencies.
